### ISSUE TITLE
Xential integratie

### ISSUE THREAD

**Issue by TjerkVaags** [GemeenteUtrecht/ZGW#555]
# CMIS issue

Kan nog steeds geen contact maken met CMIS vanuit Xential. Ik heb drie properties toegevoegd (zie containers.yml) die dit mogelijk moeten maken, maar zonder resultaat.
Weet jij misschien hoe dit kan? 

`Cannot access "https://alfresco.utrechtproeftuin.nl​​​/alfresco/api/-default-/public/cmis/versions/1.1/atom/path?path=%2FUser+Homes%2Fxential&filter=&includeAllowableActions=true&includeACL=false&includePolicyIds=false&includeRelationships=none&renditionFilter=cmis%3Anone": alfresco.utrechtproeftuin.nl​​​@/nextBASE/api/global/http with data: [ integrationid=CMISDMSHandler&dir=/&format=json&method=integration.CMIS.GetDirectories&state=Productie ]. Headers: [Content-Type: application/x-www-form-urlencoded ]
org.apache.chemistry.opencmis.commons.exceptions.CmisConnectionException: Cannot access "https://alfresco.utrechtproeftuin.nl​​​/alfresco/api/-default-/public/cmis/versions/1.1/atom/path?path=%2FUser+Homes%2Fxential&filter=&includeAllowableActions=true&includeACL=false&includePolicyIds=false&includeRelationships=none&renditionFilter=cmis%3Anone": alfresco.utrechtproeftuin.nl​​​
	at org.apache.chemistry.opencmis.client.bindings.spi.http.DefaultHttpInvoker.invoke(DefaultHttpInvoker.java:230)
	at org.apache.chemistry.opencmis.client.bindings.spi.http.DefaultHttpInvoker.invokeGET(DefaultHttpInvoker.java:57)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.read(AbstractAtomPubService.java:641)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.getObjectInternal(AbstractAtomPubService.java:868)
	at org.apache.chemistry.opencmis.client.bindings.spi.atompub.ObjectServiceImpl.getObjectByPath(ObjectServiceImpl.java:634)
	at org.apache.chemistry.opencmis.client.runtime.SessionImpl.getObjectByPath(SessionImpl.java:556)
	at org.apache.chemistry.opencmis.client.runtime.SessionImpl.getObjectByPath(SessionImpl.java:534)
	at nl.interactionnext.integration.cmis.util.CMISConnection.getDirectories(CMISConnection.java:340)
	at nl.interactionnext.integration.cmis.api.GetCMISDirectoriesApiCall.getGenericObject(GetCMISDirectoriesApiCall.java:91)
	at nl.interactionnext.base.api.GenericObjectApiCall.call(GenericObjectApiCall.java:49)
	at nl.interactionnext.base.api.ApiCall.call(ApiCall.java:109)
	at nl.interactionnext.base.api.ApiServlet.processRequest(ApiServlet.java:103)
	at nl.interactionnext.base.util.http.XServlet.service(XServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at nl.interactionnext.base.BaseFilter.doFilter(BaseFilter.java:177)
	at nl.interactionnext.base.BaseFilter.doFilter(BaseFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: alfresco.utrechtproeftuin.nl​​​
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at org.apache.chemistry.opencmis.client.bindings.spi.http.DefaultHttpInvoker.invoke(DefaultHttpInvoker.java:205)
	... 47 more`

**Comment by sergei-maertens** [comment]
Seems to be accessible for me with admin account, so the CMIS endpoint looks available.

Is this an authentication/authorization problem? Can you test out the same calls with the credentials used by Xential?

**Comment by TjerkVaags** [comment]
We used CMIS workbench to check if a simple login would work, but we get the same result. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/71717462/94258980-096df100-ff2e-11ea-9650-60323e70727c.png)

**Comment by TjerkVaags** [comment]
Hi Sergei, ik heb het probleem kunnen nabootsen op onze omgeving. Door de volgende global.properties toe te voegen werkt de koppeling:
_-Dopencmis.server.override=true
-Dopencmis.server.value=https://alfresco-oz.utrechtproeftuin.nl_
Deze properties zijn al toegevoegd op jullie omgeving, dus ik weet nu niet waarom er nog steeds geen connectie is.

**Comment by TjerkVaags** [comment]
Sorry, ik bedoel _https://alfresco.utrechtproeftuin.nl​​​_
